# Generated by Django 3.0.4 on 2020-03-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
